name: Generate Buckinghamshire bins ICS

permissions:
  contents: write   # allow the job to push to gh-pages

on:
  schedule:
    - cron: "0 9 * * 1"   # Mondays 09:00 UK time
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UPRN: "100080513727"
      COUNCIL: "BuckinghamshireCouncil"
      SOURCE_URL: "https://www.buckinghamshire.gov.uk/waste-and-recycling/find-out-when-its-your-bin-collection/"
      CAL_NAME: "Buckinghamshire Bins"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Chrome for Testing (adds google-chrome to PATH)
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show Chrome version
        run: |
          which google-chrome || true
          google-chrome --version || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install --only-binary=:all: cryptography
          python -m pip install \
            pandas holidays requests icalendar beautifulsoup4 lxml \
            selenium webdriver-manager cffi
          git clone https://github.com/robbrad/UKBinCollectionData.git ukbcd

      - name: Collect JSON (Bucks, headless Chrome)
        working-directory: ukbcd
        env:
          SE_OPTIONS: "--no-sandbox --disable-dev-shm-usage --disable-gpu --remote-allow-origins=*"
        run: |
          set -e
          python -m uk_bin_collection.uk_bin_collection.collect_data "$COUNCIL" "$SOURCE_URL" -u "$UPRN" --headless -w chrome > ../bucks.json
          test -s ../bucks.json
          head -n 30 ../bucks.json || true

      - name: Build ICS from JSON
        working-directory: ukbcd
        run: |
          python bin_to_ics.py --input ../bucks.json --output ../bins.ics --name "$CAL_NAME"
          test -s ../bins.ics
          head -n 30 ../bins.ics || true

      - name: Prepare site (gh-pages)
        run: |
          mkdir -p public
          cp bins.ics public/
          cat > public/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>Bindicator</title>
          <p>Latest <code>bins.ics</code> generated by GitHub Actions.</p>
          <p><a href="bins.ics">Download bins.ics</a></p>
          HTML

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
