name: Generate Buckinghamshire bins ICS

on:
  schedule:
    # Every Monday at 09:00 London time
    - cron: "0 9 * * 1"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UPRN: "100080513727"
      COUNCIL: "BuckinghamshireCouncil"
      SOURCE_URL: "https://www.buckinghamshire.gov.uk/waste-and-recycling/find-out-when-its-your-bin-collection/"
      CAL_NAME: "Buckinghamshire Bins"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          python -m pip install --upgrade pip
          python -m pip install pandas holidays requests icalendar beautifulsoup4 lxml selenium webdriver-manager
          git clone https://github.com/robbrad/UKBinCollectionData.git ukbcd

      - name: Run scraper to collect Bucks bin data
        working-directory: ukbcd
        run: |
          python -m uk_bin_collection.uk_bin_collection.collect_data "$COUNCIL" "$SOURCE_URL" -u "$UPRN" --headless -w chrome > ../bucks.json
          test -s ../bucks.json

      - name: Convert JSON to ICS
        working-directory: ukbcd
        run: |
          python bin_to_ics.py --input ../bucks.json --output ../bins.ics --name "$CAL_NAME"
          test -s ../bins.ics

      - name: Prepare web output
        run: |
          mkdir -p public
          cp bins.ics public/
          cat > public/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>Bindicator</title>
          <p>Latest <code>bins.ics</code> generated by GitHub Actions.</p>
          <p><a href="bins.ics">Download bins.ics</a></p>
          HTML

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
